### ISSUE TITLE
Dunno waii is/2 no work

### ISSUE THREAD

**Issue by admredbeard** [Uberpapi/PrologPoker#3]
![image](https://user-images.githubusercontent.com/26894696/31407049-ca1e361e-ae03-11e7-8d9b-e53b6986d9b2.png)

**Comment by admredbeard** [comment]
![image](https://user-images.githubusercontent.com/26894696/31442266-20aeafc6-ae96-11e7-91d2-09d83a09f365.png)

**Comment by ghost** [comment]
CLosreszx
